Improve Docker build workflow

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -3,6 +3,8 @@ name: "Docker Push"
 on:
   release:
     types: [published]
+  schedule:
+    - cron: '30 12 * * *'
 
 permissions:
   packages: write
@@ -16,15 +18,18 @@ jobs:
     name: Docker Build & Publish
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        tag: [ 'centos7', 'centos7-unprivileged' ]
+
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
       - name: Login to DockerHub
         uses: docker/login-action@v2
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-        if: ${{ env.DOCKERHUB_USERNAME != '' }}
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
@@ -36,25 +41,86 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ghcr.io/${{env.IMAGE_NAME}}
-            ${{env.IMAGE_NAME}}
-          flavor: latest=true
+      - name: Prepare metadata for build
+        id: metadata
+        run: |
+          rev=$(git rev-list --tags --max-count=1)
+          version=$(git describe --tags "$rev" | tr -d 'v')
+
+          if [[ -z "$version" ]] ; then
+            echo "::error::Can't find version info"
+            exit 1
+          fi
+
+          docker_file=".docker/${{matrix.tag}}.docker"
+          base_image=$(grep 'FROM ' $docker_file | tail -1 | cut -f1 -d' ')
+
+          if [[ -z "$base_image" ]] ; then
+            echo "::error::Can't extract base image info"
+            exit 1
+          fi
+
+          echo "::set-output name=version::$version"
+          echo "::set-output name=dockerfile::$docker_file"
+          echo "::set-output name=baseimage::$base_image"
+
+          echo -e "\033[34mVersion:\033[0m    $version"
+          echo -e "\033[34mDockerfile:\033[0m $docker_file"
+          echo -e "\033[34mBase image:\033[0m $base_image"
+
+      - name: Check if build/rebuild is required
+        id: build_check
+        run: |
+          if [[ "${{github.event_name}}" == "release" ]] ; then
+            echo "::set-output name=build::true"
+            exit 0
+          fi
+
+          echo -e "::group::\033[34mDownloading built image…\033[0m"
+
+          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}} ; then
+            echo "::error::Can't download image ${{env.IMAGE_NAME}}:${{matrix.tag}}"
+            exit 1
+          fi
+
+          echo "::endgroup::"
+          echo -e "::group::\033[34mDownloading base image…\033[0m"
+
+          if ! docker pull ${{steps.metadata.outputs.base_image}} ; then
+            echo "::error::Can't download image ${{steps.metadata.outputs.base_image}}"
+            exit 1
+          fi
+
+          echo "::endgroup::"
+
+          base_layer=$(docker inspect "${{steps.metadata.outputs.base_image}}" | jq -r '.[0].RootFS.Layers[-1]')
+
+          if [[ -z "$base_image" ]] ; then
+            echo "::error::Can't extract layers info from base image"
+            exit 1
+          fi
+
+          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
+            echo "::warning::Rebuild image (reason: base image rebuilt)"
+            echo "::set-output name=build::true"
+            exit 0
+          fi
 
       - name: Build and push Docker image
+        if: ${{ steps.build_check.outputs.build == 'true' }}
         uses: docker/build-push-action@v3
         with:
-          context: .
           push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+          context: .
+          file: ${{steps.metadata.outputs.dockerfile}}
+          tags: |
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}-${{steps.metadata.outputs.version}}
+            ${{env.IMAGE_NAME}}:${{matrix.tag}}
+            ${{env.IMAGE_NAME}}:${{matrix.tag}}-${{steps.metadata.outputs.version}}
 
       - name: Show info about built Docker image
         uses: essentialkaos/docker-info-action@v1
         with:
-          image: ${{env.IMAGE_NAME}}:latest
+          image: ${{env.IMAGE_NAME}}:${{matrix.tag}}
           show-labels: true
